# Создай файл render.yaml
services:
  - type: web
    name: videoparty
    env: go
    buildCommand: go build -o videoparty
    startCommand: ./videoparty
    envVars:
      - key: PORT
        value: 8080